apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flink-task-manager
spec:
  replicas: ${FLINK_JOB_PARALLELISM}
  template:
    metadata:
      labels:
        app: flink
        component: task-manager
    spec:
      containers:
      - name: flink-task-manager
        image: ${FLINK_IMAGE_NAME}
        args: ["task-manager", "-Djobmanager.rpc.address=flink-job-cluster"]